# Generated by Django 5.1.4 on 2024-12-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_role_user_address_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('worker', 'Работник'), ('client', 'Клиент')], default='client', max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
