   services:
     - type: web
       name: okna
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: gunicorn crm.wsgi:application --bind 0.0.0.0:$PORT
       envVars:
         - key: PYTHON_VERSION
           value: 3.9.0
         - key: DATABASE_URL
           fromDatabase:
             name: postgres
             property: connectionString

     - type: worker
       name: telegram-bot
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: python runbot.py
       envVars:
         - key: PYTHON_VERSION
           value: 3.9.0
         - key: DATABASE_URL
           fromDatabase:
             name: postgres
             property: connectionString

databases:
  - name: postgres
    databaseName: your_db_name
    user: your_db_user