# Generated by Django 5.1.4 on 2024-12-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telephone_number',
            field=models.CharField(default='88005553535', max_length=15),
        ),
    ]
