# Generated by Django 5.1.4 on 2025-01-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['phone'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='-', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='-', max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
    ]
