# Generated by Django 5.1.4 on 2025-03-04 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF файл (необязательно)', null=True, upload_to='orders_pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF файл'),
        ),
    ]
