# Generated by Django 5.1.4 on 2025-04-16 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderstatushistory_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='order',
            name='order_file',
            field=models.FileField(blank=True, help_text='Загрузите файл заказа (PDF, Excel, Word)', null=True, upload_to='orders_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'xls', 'doc', 'docx'])], verbose_name='Файл заказа'),
        ),
    ]
